# Build hacks
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
RELAX_USES_LIBRARY_CHECK=true

# Sysfs path
BOARD_COMMON_BACKLIGHT_PATH := /sys/class/backlight/sprd_backlight/brightness
BOARD_COMMON_FLASHLIGHT_PATH := "/sys/devices/virtual/misc/sprd_flash/test"
BOARD_COMMON_VIBRATOR_PATH :=

# Resetprop & repacktools
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_LIBRESETPROP := true

# Debugging
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
#TWRP_EVENT_LOGGING := true

# Kernel module
#TW_LOAD_VENDOR_MODULES := "incrementalfs.ko kheaders.ko trace_irqsoff_bytedancy.ko trace_noschedule_bytedancy.ko trace_runqlat_bytedancy.ko"

# TWRP Configuration
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := id
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_NO_HAPTICS := true
TW_NO_FLASH_CURRENT_TWRP := true
TW_BRIGHTNESS_PATH := $(BOARD_COMMON_BACKLIGHT_PATH)
TW_DEFAULT_BRIGHTNESS := 150
TW_MAX_BRIGHTNESS := 4000
TW_INCLUDE_FASTBOOTD := true
TW_INCLUDE_NTFS_3G := true
TW_USE_TOOLBOX := true
RECOVERY_SDCARD_ON_DATA := true
TW_USE_EXTERNAL_STORAGE := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := false
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_TWRPAPP := true
TW_NO_BIND_SYSTEM := true
#TW_NO_SCREEN_BLANK := false
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_LEGACY_PROPS := true
TW_OVERRIDE_SYSTEM_PROPS := "ro.build.version.sdk"
TARGET_USE_CUSTOM_LUN_FILE_PATH := /config/usb_gadget/g1/functions/mass_storage.usb0/lun.%d/file
#TW_LOAD_VENDOR_BOOT_MODULES := true
#TW_LOAD_VENDOR_MODULES_EXCLUDE_GKI := true

# Fix fastboot reboot
TW_NO_FASTBOOT_BOOT := true

# TWRP Fix Clock,Cpu temp, battery persentase position
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := 50
TW_CUSTOM_CLOCK_POS := 300
TW_CUSTOM_BATTERY_POS := 800

# PBRP Configuration
PBRP_DEVICE := RMX3506
PBRP_DEFAULT_LANG := in
PB_DISABLE_DEFAULT_DM_VERITY := true
BETA_BUILD := true
PB_TORCH_PATH := $(BOARD_COMMON_FLASHLIGHT_PATH)
PB_VIBRATOR_PATH := $(BOARD_COMMON_VIBRATOR_PATH)

# OrangeFox Configuration
FOX_VIRTUAL_AB_DEVICE := true
#OF_FIX_DECRYPTION_ON_DATA_MEDIA := true
#FOX_USE_DATA_RECOVERY_FOR_SETTINGS := true
FOX_BUILD_DEVICE := RMX3506
OF_DEFAULT_LANG := id
OF_FLASHLIGHT_ENABLE := true
OF_FL_PATH1 := $(BOARD_COMMON_FLASHLIGHT_PATH)
OF_VIBRATOR_ENABLE := false
#OF_VIBRATOR_PATH := 
OF_HIDE_NOTCH := true
OF_KEEP_DM_VERITY := true
OF_CLOCK_POS := 1
OF_STATUS_INDENT_LEFT := 50
OF_STATUS_INDENT_RIGHT := 50
OF_NO_REFLASH_CURRENT_ORANGEFOX := true

# SHRP Reborn Configuration
SHRP_DEVICE_CODE := RMX3506
SHRP_PATH := device/realme/$(SHRP_DEVICE_CODE)
SHRP_REC_TYPE := SAR
SHRP_DEVICE_TYPE := A/B
SHRP_AB := true
SHRP_FLASH := 1
SHRP_CUSTOM_FLASHLIGHT := true
SHRP_FONP_1 := $(BOARD_COMMON_FLASHLIGHT_PATH)
SHRP_INTERNAL := /sdcard
SHRP_EXTERNAL := /external_sd
SHRP_OTG := /usb_otg
SHRP_EXPRESS := true
SHRP_DARK := true


# Maintainer
BOARD_MAINTAINER_NAME := RMX3506-Aflahal
TW_DEVICE_VERSION := $(BOARD_MAINTAINER_NAME)
PB_MAIN_VERSION := $(BOARD_MAINTAINER_NAME)
OF_MAINTAINER := $(BOARD_MAINTAINER_NAME)
SHRP_MAINTAINER := $(BOARD_MAINTAINER_NAME)